### ISSUE TITLE
Redundant library

### ISSUE THREAD

**Issue by hienvuvg** [dproldan/Esp32AutoCamera#6]
Thank you. It works great for me. 
There is an error with library dl_lib.h. Please remove it!
I also think it's better to add wifi password to the code. I did it and it works fine too.

**Comment by javivi1** [comment]
Please, can you tell me what is the solution of this problem which; dl_lib.h ?????

**Comment by hienvuvg** [comment]
Hi, you need to delete that line and the code will run just fine

**Comment by dproldan** [comment]
removed dl_lib
